name: scrape

on:
  workflow_dispatch:
  schedule:
    # JST: 0, 6, 12, 18 -> UTC: 15, 21, 3, 9
    - cron: "0 15 * * *"
    - cron: "0 21 * * *"
    - cron: "0 3 * * *"
    - cron: "0 9 * * *"

jobs:
  Scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run robot script
        run: |
          python robot.py
        env:
          USER_NAME: ${{ secrets.USER_NAME }}

      - name: Commit files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
